vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|22 Feb 2001 16:25:06 -0000
vti_extenderversion:SR|4.0.2.4022
vti_nexttolasttimemodified:TR|22 Feb 2001 16:30:15 -0000
vti_author:SR|usr125068
vti_modifiedby:SR|usr125068
vti_timecreated:TR|03 Apr 2001 13:06:38 -0000
vti_backlinkinfo:VX|
vti_syncwith_localhost\\w\:/w\::TR|22 Feb 2001 16:30:15 -0000
vti_syncwith_www.bbbsa.org\:80:TR|22 Feb 2001 16:25:06 -0000
