vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|16 Feb 2001 23:03:11 -0000
vti_extenderversion:SR|4.0.2.4022
vti_nexttolasttimemodified:TR|04 Feb 2001 19:39:20 -0000
vti_author:SR|usr125068
vti_modifiedby:SR|usr125068
vti_timecreated:TR|03 Apr 2001 13:06:38 -0000
vti_backlinkinfo:VX|
vti_syncwith_localhost\\w\:/w\::TR|04 Feb 2001 19:39:20 -0000
vti_syncwith_www.bbbsa.org\:80:TR|16 Feb 2001 23:03:11 -0000
